'use client';
import { useCallback, useEffect, useState } from 'react';
type Tenant = { id: string; name: string; phoneNormalized: string; email?: string };
type Property = { id: string; propertyCode: string; displayName: string };
type Agreement = { id: string; agreementNumber: string; status: string; monthlyRent: string; tenant: Tenant; property: Property; startDate: string; endDate: string };
type Bill = { id: string; billNumber: string; status: string; totalAmount: string; paidAmount: string; balanceAmount: string; dueDate: string; agreement: { tenant: Tenant; property: Property } };
type Payment = { id: string; paymentNumber: string; amount: string; status: string; receivedAt: string; tenant: Tenant; receipt?: { receiptNumber: string } };
type Envelope<T> = { data?: T; error?: { message: string } }; function csrf(): string { return decodeURIComponent(document.cookie.split('; ').find((x) => x.startsWith('ems_csrf_token='))?.split('=')[1] ?? ''); }
export default function ShopBillingPage(): React.ReactElement { const [tab, setTab] = useState<'tenants'|'agreements'|'bills'|'payments'>('tenants'); const [tenants, setTenants] = useState<Tenant[]>([]); const [properties, setProperties] = useState<Property[]>([]); const [agreements, setAgreements] = useState<Agreement[]>([]); const [bills, setBills] = useState<Bill[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [message, setMessage] = useState<string>(); const load = useCallback(async () => { const [t,p,a,b,pay] = await Promise.all(['/api/v1/shop-tenants','/api/v1/properties?pageSize=100','/api/v1/shop-agreements','/api/v1/bills','/api/v1/payments'].map((url) => fetch(url).then((r) => r.json()))); setTenants((t as Envelope<Tenant[]>).data ?? []); setProperties((p as Envelope<Property[]>).data ?? []); setAgreements((a as Envelope<Agreement[]>).data ?? []); setBills((b as Envelope<Bill[]>).data ?? []); setPayments((pay as Envelope<Payment[]>).data ?? []); }, []); useEffect(() => { void Promise.all(['/api/v1/shop-tenants','/api/v1/properties?pageSize=100','/api/v1/shop-agreements','/api/v1/bills','/api/v1/payments'].map((url) => fetch(url).then((r) => r.json()))).then(([t,p,a,b,pay]) => { setTenants((t as Envelope<Tenant[]>).data ?? []); setProperties((p as Envelope<Property[]>).data ?? []); setAgreements((a as Envelope<Agreement[]>).data ?? []); setBills((b as Envelope<Bill[]>).data ?? []); setPayments((pay as Envelope<Payment[]>).data ?? []); }); }, []);
async function post(url: string, body: unknown): Promise<boolean> { const response = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify(body) }); const payload = await response.json() as Envelope<unknown>; setMessage(response.ok ? 'Operation completed.' : payload.error?.message ?? 'Operation failed'); if (response.ok) await load(); return response.ok; }
async function createTenant(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); if (await post('/api/v1/shop-tenants', { name:f.get('name'),cnic:f.get('cnic'),phone:f.get('phone'),email:f.get('email')||undefined,address:f.get('address') })) e.currentTarget.reset(); }
async function createAgreement(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); if (await post('/api/v1/shop-agreements', { propertyId:f.get('propertyId'),tenantId:f.get('tenantId'),startDate:f.get('startDate'),endDate:f.get('endDate'),monthlyRent:Number(f.get('monthlyRent')),securityDeposit:Number(f.get('securityDeposit')),gracePeriodDays:5,lateFeePercent:2,annualEscalationPercent:10,activate:true,utilityRules:[] })) e.currentTarget.reset(); }
async function createBill(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const start = new Date(String(f.get('periodStart'))); const end = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth()+1, 0)); const due = new Date(start); due.setUTCDate(due.getUTCDate()+10); if (await post('/api/v1/bills', { agreementId:f.get('agreementId'),periodStart:start,periodEnd:end,issueDate:start,dueDate:due,utilityUsage:{},adjustments:[],issue:true })) e.currentTarget.reset(); }
async function createPayment(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const bill = bills.find((x) => x.id === f.get('billId')); if (!bill) return; if (await post('/api/v1/payments', { tenantId:bill.agreement.tenant.id,amount:Number(f.get('amount')),paymentMethod:f.get('paymentMethod'),receivedAt:new Date(),allocations:[{billId:bill.id,amount:Number(f.get('amount'))}] })) e.currentTarget.reset(); }
return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">Shop management and billing</h1><p className="text-sm text-slate-600 dark:text-slate-300">Tenants, agreements, monthly bills, arrears, payments, and receipts.</p></header><div className="flex gap-2 overflow-x-auto">{(['tenants','agreements','bills','payments'] as const).map((x)=><button key={x} onClick={()=>setTab(x)} className={`rounded-lg px-3 py-2 capitalize ${tab===x?'bg-red-600 text-white':'border'}`}>{x}</button>)}</div>{message?<p role="status" className="rounded-lg border p-3 text-sm">{message}</p>:null}
{tab==='tenants'?<section className="space-y-4"><form onSubmit={createTenant} className="grid gap-3 rounded-2xl border bg-white p-4 dark:bg-slate-900 md:grid-cols-2 xl:grid-cols-5"><input required name="name" placeholder="Tenant name" className="rounded-lg border bg-transparent p-2"/><input required name="cnic" placeholder="CNIC" className="rounded-lg border bg-transparent p-2"/><input required name="phone" placeholder="Phone" className="rounded-lg border bg-transparent p-2"/><input name="email" type="email" placeholder="Email" className="rounded-lg border bg-transparent p-2"/><input required name="address" placeholder="Address" className="rounded-lg border bg-transparent p-2"/><button className="rounded-lg bg-red-600 p-2 text-white">Add tenant</button></form><Cards rows={tenants.map(x=>({title:x.name,detail:`${x.phoneNormalized}${x.email?` · ${x.email}`:''}`}))}/></section>:null}
{tab==='agreements'?<section className="space-y-4"><form onSubmit={createAgreement} className="grid gap-3 rounded-2xl border bg-white p-4 dark:bg-slate-900 md:grid-cols-2 xl:grid-cols-4"><select required name="propertyId" className="rounded-lg border bg-transparent p-2"><option value="">Shop property</option>{properties.map(x=><option key={x.id} value={x.id}>{x.propertyCode} — {x.displayName}</option>)}</select><select required name="tenantId" className="rounded-lg border bg-transparent p-2"><option value="">Tenant</option>{tenants.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required name="startDate" type="date" className="rounded-lg border bg-transparent p-2"/><input required name="endDate" type="date" className="rounded-lg border bg-transparent p-2"/><input required name="monthlyRent" type="number" min="0" placeholder="Monthly rent PKR" className="rounded-lg border bg-transparent p-2"/><input required name="securityDeposit" type="number" min="0" placeholder="Security deposit" className="rounded-lg border bg-transparent p-2"/><button className="rounded-lg bg-red-600 p-2 text-white">Activate agreement</button></form><Cards rows={agreements.map(x=>({title:x.agreementNumber,detail:`${x.property.displayName} · ${x.tenant.name} · PKR ${x.monthlyRent} · ${x.status}`}))}/></section>:null}
{tab==='bills'?<section className="space-y-4"><form onSubmit={createBill} className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4 dark:bg-slate-900"><select required name="agreementId" className="min-w-64 rounded-lg border bg-transparent p-2"><option value="">Active agreement</option>{agreements.filter(x=>x.status==='ACTIVE').map(x=><option key={x.id} value={x.id}>{x.agreementNumber} — {x.tenant.name}</option>)}</select><input required name="periodStart" type="date" className="rounded-lg border bg-transparent p-2"/><button className="rounded-lg bg-red-600 p-2 text-white">Generate monthly bill</button></form><Cards rows={bills.map(x=>({title:x.billNumber,detail:`${x.agreement.tenant.name} · Total PKR ${x.totalAmount} · Balance PKR ${x.balanceAmount} · ${x.status}`}))}/></section>:null}
{tab==='payments'?<section className="space-y-4"><form onSubmit={createPayment} className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4 dark:bg-slate-900"><select required name="billId" className="min-w-64 rounded-lg border bg-transparent p-2"><option value="">Outstanding bill</option>{bills.filter(x=>Number(x.balanceAmount)>0).map(x=><option key={x.id} value={x.id}>{x.billNumber} — PKR {x.balanceAmount}</option>)}</select><input required name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" className="rounded-lg border bg-transparent p-2"/><select name="paymentMethod" className="rounded-lg border bg-transparent p-2"><option>BANK_TRANSFER</option><option>CHEQUE</option><option>CASH</option></select><button className="rounded-lg bg-red-600 p-2 text-white">Record payment</button></form><Cards rows={payments.map(x=>({title:x.paymentNumber,detail:`${x.tenant.name} · PKR ${x.amount} · ${x.status}`,href:x.receipt?`/api/v1/payments/${x.id}/receipt`:undefined}))}/></section>:null}</div>; }
function Cards({rows}:{rows:Array<{title:string;detail:string;href?:string}>}):React.ReactElement{return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(x=><article key={x.title} className="rounded-xl border bg-white p-4 dark:bg-slate-900"><strong>{x.title}</strong><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{x.detail}</p>{x.href?<a target="_blank" href={x.href} className="mt-2 inline-block text-sm text-red-700">Open receipt</a>:null}</article>)}</div>}
