import { randomBytes } from 'crypto';
import { Prisma, type AllocationStatus } from '@prisma/client';
import type { ListQuery } from '../api/list-query';
import { writeAuditLog } from '../audit/service';
import { prisma } from '../db/prisma';
import type { AllocationCreateInput } from './schemas';
type Actor = { userId: string; requestId?: string; ipAddress?: string; userAgent?: string };
const include = { property: { include: { building: true, floor: true, propertyType: true, inventoryAssignments: { where: { returnedAt: null }, include: { item: true } } } }, department: true, approver: { select: { displayName: true } }, history: { include: { actor: { select: { displayName: true } } }, orderBy: { createdAt: 'asc' as const } } };
function reference(): string { return `AL-${new Date().toISOString().slice(0, 10).replaceAll('-', '')}-${randomBytes(3).toString('hex').toUpperCase()}`; }
async function history(tx: Prisma.TransactionClient, allocationId: string, fromStatus: AllocationStatus | null, toStatus: AllocationStatus, departmentId: string, responsiblePerson: string | null, actor: Actor, reason?: string) { await tx.allocationHistory.create({ data: { allocationId, fromStatus, toStatus, departmentId, responsiblePerson, effectiveAt: new Date(), reason, actorUserId: actor.userId } }); }
export async function listAllocations(query: ListQuery, status?: AllocationStatus) { const where: Prisma.AllocationWhereInput = { ...(status ? { status } : {}), ...(query.search ? { OR: [{ referenceNumber: { contains: query.search, mode: 'insensitive' } }, { responsiblePerson: { contains: query.search, mode: 'insensitive' } }, { property: { displayName: { contains: query.search, mode: 'insensitive' } } }, { department: { name: { contains: query.search, mode: 'insensitive' } } }] } : {}) }; const [rows, total] = await prisma.$transaction([prisma.allocation.findMany({ where, include, orderBy: { createdAt: 'desc' }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.allocation.count({ where })]); return { rows, total }; }
export async function getAllocation(id: string) { return prisma.allocation.findUnique({ where: { id }, include }); }
export async function createAllocation(input: AllocationCreateInput, actor: Actor) { const property = await prisma.property.findFirst({ where: { id: input.propertyId, deletedAt: null, operationalStatus: 'ACTIVE' } }); if (!property) throw new Error('ALLOCATION_PROPERTY_UNAVAILABLE'); const status: AllocationStatus = input.submit ? 'PENDING_APPROVAL' : 'DRAFT'; const created = await prisma.$transaction(async (tx) => { const row = await tx.allocation.create({ data: { referenceNumber: reference(), propertyId: input.propertyId, departmentId: input.departmentId, responsiblePerson: input.responsiblePerson, requestDate: input.requestDate, startDate: input.startDate, endDate: input.endDate, notes: input.notes, status, createdBy: actor.userId, updatedBy: actor.userId } }); await history(tx, row.id, null, status, row.departmentId, row.responsiblePerson, actor); return tx.allocation.findUniqueOrThrow({ where: { id: row.id }, include }); }); await writeAuditLog({ actorUserId: actor.userId, action: input.submit ? 'ALLOCATION_SUBMIT' : 'ALLOCATION_CREATE', entityType: 'Allocation', entityId: created.id, afterData: created }); return created; }
export async function transitionAllocation(id: string, action: 'submit' | 'approve' | 'activate' | 'vacate' | 'cancel', actor: Actor, reason?: string) { const before = await getAllocation(id); if (!before) throw new Error('ALLOCATION_NOT_FOUND'); const allowed: Record<typeof action, AllocationStatus[]> = { submit: ['DRAFT'], approve: ['PENDING_APPROVAL'], activate: ['APPROVED'], vacate: ['ACTIVE'], cancel: ['DRAFT', 'PENDING_APPROVAL', 'APPROVED'] }; if (!allowed[action].includes(before.status)) throw new Error('ALLOCATION_INVALID_TRANSITION'); const target: Record<typeof action, AllocationStatus> = { submit: 'PENDING_APPROVAL', approve: 'APPROVED', activate: 'ACTIVE', vacate: 'VACATED', cancel: 'CANCELLED' }; const toStatus = target[action]; const updated = await prisma.$transaction(async (tx) => { if (action === 'activate') { const active = await tx.allocation.findFirst({ where: { propertyId: before.propertyId, status: 'ACTIVE' } }); if (active) throw new Error('ALLOCATION_ACTIVE_CONFLICT'); } const row = await tx.allocation.update({ where: { id }, data: { status: toStatus, approvedBy: action === 'approve' ? actor.userId : before.approvedBy, approvedAt: action === 'approve' ? new Date() : before.approvedAt, startDate: action === 'activate' ? (before.startDate ?? new Date()) : before.startDate, endDate: action === 'vacate' ? new Date() : before.endDate, updatedBy: actor.userId } }); if (action === 'activate' || action === 'vacate') await tx.property.update({ where: { id: before.propertyId }, data: { occupancyStatus: action === 'activate' ? 'OCCUPIED' : 'VACANT', updatedBy: actor.userId } }); await history(tx, id, before.status, toStatus, row.departmentId, row.responsiblePerson, actor, reason); return tx.allocation.findUniqueOrThrow({ where: { id }, include }); }, { isolationLevel: 'Serializable' }); await writeAuditLog({ actorUserId: actor.userId, action: `ALLOCATION_${toStatus}`, entityType: 'Allocation', entityId: id, beforeData: before, afterData: updated }); return updated; }
export async function reassignAllocation(id: string, departmentId: string, responsiblePerson: string | undefined, reason: string, actor: Actor) { const before = await getAllocation(id); if (!before) throw new Error('ALLOCATION_NOT_FOUND'); if (before.status !== 'ACTIVE') throw new Error('ALLOCATION_INVALID_TRANSITION'); const created = await prisma.$transaction(async (tx) => { const closed = await tx.allocation.update({ where: { id }, data: { status: 'REASSIGNED', endDate: new Date(), updatedBy: actor.userId } }); await history(tx, id, 'ACTIVE', 'REASSIGNED', closed.departmentId, closed.responsiblePerson, actor, reason); const next = await tx.allocation.create({ data: { referenceNumber: reference(), propertyId: before.propertyId, departmentId, responsiblePerson, requestDate: new Date(), startDate: new Date(), status: 'ACTIVE', approvedBy: actor.userId, approvedAt: new Date(), createdBy: actor.userId, updatedBy: actor.userId, notes: `Reassigned from ${before.referenceNumber}: ${reason}` } }); await history(tx, next.id, null, 'ACTIVE', departmentId, responsiblePerson ?? null, actor, reason); return tx.allocation.findUniqueOrThrow({ where: { id: next.id }, include }); }, { isolationLevel: 'Serializable' }); await writeAuditLog({ actorUserId: actor.userId, action: 'ALLOCATION_REASSIGN', entityType: 'Allocation', entityId: id, beforeData: before, afterData: created }); return created; }
