'use client';
import { useCallback, useEffect, useState } from 'react';

type Employee = { id:string; employeeNumber:string; name:string; designation:string; retirementDate:string; grade:{code:string} };
type Property = { id:string; propertyCode:string; displayName:string };
type Master = { grades:Array<{id:string;code:string}>; categories:Array<{id:string;code:string;name:string;minimumGradeRank:number;maximumGradeRank:number}>; flats:Array<{propertyId:string;block:string;property:Property;category:{code:string}}> };
type Allocation = { id:string;referenceNumber:string;status:string;expectedVacationDate:string;employee:Employee;property:Property;extensions:Array<{id:string;originalVacationDate:string;revisedVacationDate:string;reason:string}>;history:Array<{id:string;fromStatus?:string;toStatus:string;reason?:string;actor:{displayName:string}}> };
type Option={id:string;name?:string}; type Envelope<T>={data?:T;error?:{message:string}};
const emptyMaster:Master={grades:[],categories:[],flats:[]};
function csrf():string{return decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('ems_csrf_token='))?.split('=')[1]??'');}
function date(value:string):string{return new Date(value).toLocaleDateString('en-PK',{timeZone:'UTC'});}

export default function FlatsPage():React.ReactElement{
  const [tab,setTab]=useState<'allocations'|'employees'|'setup'|'alerts'>('allocations'); const [employees,setEmployees]=useState<Employee[]>([]); const [properties,setProperties]=useState<Property[]>([]); const [departments,setDepartments]=useState<Option[]>([]); const [master,setMaster]=useState<Master>(emptyMaster); const [rows,setRows]=useState<Allocation[]>([]); const [alerts,setAlerts]=useState<Allocation[]>([]); const [permissions,setPermissions]=useState<string[]>([]); const [message,setMessage]=useState<string>();
  const load=useCallback(async()=>{const [e,p,d,m,a,r,s]=await Promise.all(['/api/v1/employees','/api/v1/properties?pageSize=200','/api/v1/master-data/departments?pageSize=200','/api/v1/flat-masters','/api/v1/flat-allocations','/api/v1/flat-alerts?days=60','/api/v1/auth/session'].map(url=>fetch(url).then(x=>x.json())));setEmployees((e as Envelope<Employee[]>).data??[]);setProperties((p as Envelope<Property[]>).data??[]);setDepartments((d as Envelope<Option[]>).data??[]);setMaster((m as Envelope<Master>).data??emptyMaster);setRows((a as Envelope<Allocation[]>).data??[]);setAlerts((r as Envelope<Allocation[]>).data??[]);setPermissions((s as Envelope<{user?:{permissions:string[]}}>).data?.user?.permissions??[]);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function post(url:string,body:unknown):Promise<boolean>{const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf()},body:JSON.stringify(body)});const payload=await response.json() as Envelope<unknown>;setMessage(response.ok?'Operation completed.':payload.error?.message??'Operation failed');if(response.ok)await load();return response.ok;}
  async function addEmployee(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post('/api/v1/employees',{employeeNumber:f.get('employeeNumber'),name:f.get('name'),gradeId:f.get('gradeId'),designation:f.get('designation'),departmentId:f.get('departmentId'),phone:f.get('phone'),cnic:f.get('cnic'),retirementDate:f.get('retirementDate')}))e.currentTarget.reset();}
  async function setup(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post('/api/v1/flat-masters',{propertyId:f.get('propertyId'),categoryId:f.get('categoryId'),block:f.get('block')}))e.currentTarget.reset();}
  async function allocate(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post('/api/v1/flat-allocations',{propertyId:f.get('propertyId'),employeeId:f.get('employeeId'),allocationDate:f.get('allocationDate'),notes:f.get('notes')||undefined,submit:true}))e.currentTarget.reset();}
  async function action(row:Allocation,name:string){let body:Record<string,unknown>={};if(['vacate','cancel'].includes(name)){const reason=prompt('Reason');if(!reason)return;body={reason};}if(name==='transfer'){const propertyId=prompt('New configured flat property ID');const reason=prompt('Transfer reason');if(!propertyId||!reason)return;body={propertyId,reason};}if(name==='extend'){const revisedVacationDate=prompt('Revised vacation date (YYYY-MM-DD)');const reason=prompt('Extension reason');const approvingAuthority=prompt('Approving authority');if(!revisedVacationDate||!reason||!approvingAuthority)return;body={revisedVacationDate,reason,approvingAuthority};}await post(`/api/v1/flat-allocations/${row.id}/${name}`,body);}
  const canManage=permissions.includes('flat.manage'),canApprove=permissions.includes('flat.approve');
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">Residential flats</h1><p className="text-sm text-slate-600">Grade eligibility, approval, possession, transfer, vacation, extensions, and retirement alerts.</p></header><div className="flex gap-2 overflow-x-auto">{(['allocations','employees','setup','alerts'] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-lg px-3 py-2 capitalize ${tab===x?'bg-red-600 text-white':'border'}`}>{x}{x==='alerts'?` (${alerts.length})`:''}</button>)}</div>{message?<p role="status" className="rounded-lg border p-3 text-sm">{message}</p>:null}
  {tab==='employees'?<section className="space-y-4"><form onSubmit={addEmployee} className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-2 xl:grid-cols-4"><input required name="employeeNumber" placeholder="Employee number" className="rounded-lg border p-2"/><input required name="name" placeholder="Employee name" className="rounded-lg border p-2"/><select required name="gradeId" className="rounded-lg border p-2"><option value="">Grade</option>{master.grades.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><input required name="designation" placeholder="Designation" className="rounded-lg border p-2"/><select required name="departmentId" className="rounded-lg border p-2"><option value="">Department</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required name="phone" placeholder="Phone" className="rounded-lg border p-2"/><input required name="cnic" placeholder="CNIC 12345-1234567-1" className="rounded-lg border p-2"/><input required name="retirementDate" type="date" className="rounded-lg border p-2"/><button disabled={!canManage} className="rounded-lg bg-red-600 p-2 text-white disabled:opacity-50">Add employee</button></form><Cards rows={employees.map(x=>({title:`${x.employeeNumber} — ${x.name}`,detail:`${x.grade.code} · ${x.designation} · retirement ${date(x.retirementDate)}`}))}/></section>:null}
  {tab==='setup'?<section className="space-y-4"><form onSubmit={setup} className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><select required name="propertyId" className="min-w-64 rounded-lg border p-2"><option value="">Residential property</option>{properties.filter(x=>!master.flats.some(f=>f.propertyId===x.id)).map(x=><option key={x.id} value={x.id}>{x.propertyCode} — {x.displayName}</option>)}</select><select required name="categoryId" className="rounded-lg border p-2"><option value="">Flat category</option>{master.categories.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><input required name="block" placeholder="Block" className="rounded-lg border p-2"/><button disabled={!canManage} className="rounded-lg bg-red-600 p-2 text-white disabled:opacity-50">Configure flat</button></form><Cards rows={master.flats.map(x=>({title:`${x.property.propertyCode} — ${x.property.displayName}`,detail:`Block ${x.block} · Category ${x.category.code}`}))}/></section>:null}
  {tab==='allocations'?<section className="space-y-4"><form onSubmit={allocate} className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-2 xl:grid-cols-4"><select required name="employeeId" className="rounded-lg border p-2"><option value="">Employee</option>{employees.map(x=><option key={x.id} value={x.id}>{x.employeeNumber} — {x.name} ({x.grade.code})</option>)}</select><select required name="propertyId" className="rounded-lg border p-2"><option value="">Configured flat</option>{master.flats.map(x=><option key={x.propertyId} value={x.propertyId}>{x.property.propertyCode} — category {x.category.code}</option>)}</select><input required name="allocationDate" type="date" className="rounded-lg border p-2"/><input name="notes" placeholder="Notes" className="rounded-lg border p-2"/><button disabled={!canManage} className="rounded-lg bg-red-600 p-2 text-white disabled:opacity-50">Submit allocation</button></form>{rows.map(row=><AllocationCard key={row.id} row={row} canManage={canManage} canApprove={canApprove} action={action}/>)}</section>:null}
  {tab==='alerts'?<section className="space-y-3"><p className="text-sm">Active flats due for vacation within 60 days, including overdue cases.</p>{alerts.length?<>{alerts.map(row=><AllocationCard key={row.id} row={row} canManage={canManage} canApprove={canApprove} action={action}/>)}</>:<p className="rounded-xl border p-4">No retirement vacation alerts.</p>}</section>:null}</div>;
}
function AllocationCard({row,canManage,canApprove,action}:{row:Allocation;canManage:boolean;canApprove:boolean;action:(row:Allocation,name:string)=>Promise<void>}):React.ReactElement{return <article className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{row.referenceNumber}</strong><p>{row.property.propertyCode} — {row.employee.name} ({row.employee.grade.code})</p><p className="text-sm text-slate-500">Vacation due {date(row.expectedVacationDate)}</p></div><span className="font-medium">{row.status.replaceAll('_',' ')}</span></div><div className="mt-3 flex flex-wrap gap-3 text-sm">{row.status==='PENDING_APPROVAL'&&canApprove?<button onClick={()=>void action(row,'approve')} className="text-green-700">Approve</button>:null}{row.status==='APPROVED'&&canManage?<button onClick={()=>void action(row,'possess')} className="text-blue-700">Record possession</button>:null}{row.status==='ACTIVE'&&canManage?<><button onClick={()=>void action(row,'vacate')} className="text-red-700">Vacate</button><button onClick={()=>void action(row,'transfer')} className="text-blue-700">Transfer</button></>:null}{['APPROVED','ACTIVE'].includes(row.status)&&canApprove?<button onClick={()=>void action(row,'extend')} className="text-amber-700">Extend</button>:null}<a target="_blank" href={`/api/v1/flat-allocations/${row.id}/notice`} className="text-slate-700">Vacation notice</a></div><details className="mt-4"><summary className="cursor-pointer text-sm font-medium">History ({row.history.length}) and extensions ({row.extensions.length})</summary><ol className="mt-2 space-y-1 border-l pl-4 text-sm">{row.history.map(h=><li key={h.id}>{h.fromStatus?`${h.fromStatus} → `:''}{h.toStatus} · {h.actor.displayName}{h.reason?` · ${h.reason}`:''}</li>)}{row.extensions.map(x=><li key={x.id}>Extension: {date(x.originalVacationDate)} → {date(x.revisedVacationDate)} · {x.reason}</li>)}</ol></details></article>}
function Cards({rows}:{rows:Array<{title:string;detail:string}>}):React.ReactElement{return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(x=><article key={x.title} className="rounded-xl border bg-white p-4"><strong>{x.title}</strong><p className="mt-1 text-sm text-slate-600">{x.detail}</p></article>)}</div>}
