import { z } from 'zod';
export const tenantSchema = z.object({ name: z.string().trim().min(2).max(150), cnic: z.string().trim().regex(/^\d{5}-?\d{7}-?\d$/), phone: z.string().trim().min(10).max(20), email: z.string().trim().toLowerCase().email().optional(), address: z.string().trim().min(5).max(500), emergencyContact: z.string().trim().max(100).optional() });
export const agreementSchema = z.object({ propertyId: z.string().uuid(), tenantId: z.string().uuid(), startDate: z.coerce.date(), endDate: z.coerce.date(), monthlyRent: z.coerce.number().min(0), securityDeposit: z.coerce.number().min(0), gracePeriodDays: z.number().int().min(0).max(60).default(0), lateFeePercent: z.coerce.number().min(0).max(100).default(0), annualEscalationPercent: z.coerce.number().min(0).max(100).default(0), notes: z.string().trim().max(2000).optional(), activate: z.boolean().default(false), utilityRules: z.array(z.object({ utilityType: z.string().trim().min(2).max(50), billingMode: z.enum(['FIXED', 'METERED']), fixedAmount: z.coerce.number().min(0).optional(), unitRate: z.coerce.number().min(0).optional() })).default([]) }).refine((x) => x.endDate >= x.startDate, { path: ['endDate'], message: 'Agreement end must not precede start' });
export const billSchema = z.object({ agreementId: z.string().uuid(), periodStart: z.coerce.date(), periodEnd: z.coerce.date(), issueDate: z.coerce.date().default(() => new Date()), dueDate: z.coerce.date(), utilityUsage: z.record(z.string(), z.coerce.number().min(0)).default({}), adjustments: z.array(z.object({ description: z.string().trim().min(2), amount: z.coerce.number() })).default([]), issue: z.boolean().default(true) });
export const paymentSchema = z.object({ tenantId: z.string().uuid(), amount: z.coerce.number().positive(), paymentMethod: z.string().trim().min(2).max(50), transactionReference: z.string().trim().max(100).optional(), receivedAt: z.coerce.date().default(() => new Date()), notes: z.string().trim().max(1000).optional(), allocations: z.array(z.object({ billId: z.string().uuid(), amount: z.coerce.number().positive() })).default([]) });
export const reversalSchema = z.object({ reason: z.string().trim().min(5).max(1000) });
export function normalizeCnic(value: string): string { return value.replace(/\D/g, ''); }
export function normalizePhone(value: string): string { const digits = value.replace(/\D/g, ''); return digits.startsWith('0') ? `92${digits.slice(1)}` : digits.startsWith('92') ? digits : `92${digits}`; }
export type TenantInput = z.infer<typeof tenantSchema>; export type AgreementInput = z.infer<typeof agreementSchema>; export type BillInput = z.infer<typeof billSchema>; export type PaymentInput = z.infer<typeof paymentSchema>;
