CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE TYPE "BookingStatus" AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', 'EXPIRED');
CREATE TYPE "BookingDecision" AS ENUM ('SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED');
CREATE TABLE "Booking" ("id" TEXT NOT NULL, "referenceNumber" TEXT NOT NULL, "requestingDepartmentId" TEXT, "requesterName" TEXT NOT NULL, "requesterEmail" TEXT, "requesterPhone" TEXT, "purpose" TEXT NOT NULL, "startAt" TIMESTAMP(3) NOT NULL, "endAt" TIMESTAMP(3) NOT NULL, "attendeeCount" INTEGER NOT NULL DEFAULT 0, "isPaid" BOOLEAN NOT NULL DEFAULT false, "chargeAmount" DECIMAL(14,2), "status" "BookingStatus" NOT NULL DEFAULT 'DRAFT', "idempotencyKey" TEXT, "rejectionReason" TEXT, "cancellationReason" TEXT, "notes" TEXT, "createdBy" TEXT NOT NULL, "updatedBy" TEXT NOT NULL, "submittedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Booking_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BookingResource" ("id" TEXT NOT NULL, "bookingId" TEXT NOT NULL, "propertyId" TEXT NOT NULL, "startAt" TIMESTAMP(3) NOT NULL, "endAt" TIMESTAMP(3) NOT NULL, "status" "BookingStatus" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "BookingResource_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BookingApproval" ("id" TEXT NOT NULL, "bookingId" TEXT NOT NULL, "actorUserId" TEXT NOT NULL, "decision" "BookingDecision" NOT NULL, "remarks" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "BookingApproval_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ClosureWindow" ("id" TEXT NOT NULL, "propertyId" TEXT, "startAt" TIMESTAMP(3) NOT NULL, "endAt" TIMESTAMP(3) NOT NULL, "reason" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ClosureWindow_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "entityType" TEXT, "entityId" TEXT, "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Booking_referenceNumber_key" ON "Booking"("referenceNumber");
CREATE UNIQUE INDEX "Booking_idempotencyKey_key" ON "Booking"("idempotencyKey");
CREATE INDEX "Booking_status_startAt_idx" ON "Booking"("status", "startAt");
CREATE INDEX "Booking_requestingDepartmentId_idx" ON "Booking"("requestingDepartmentId");
CREATE INDEX "Booking_createdBy_createdAt_idx" ON "Booking"("createdBy", "createdAt");
CREATE UNIQUE INDEX "BookingResource_bookingId_propertyId_key" ON "BookingResource"("bookingId", "propertyId");
CREATE INDEX "BookingResource_propertyId_startAt_endAt_idx" ON "BookingResource"("propertyId", "startAt", "endAt");
CREATE INDEX "BookingResource_status_idx" ON "BookingResource"("status");
CREATE INDEX "BookingApproval_bookingId_createdAt_idx" ON "BookingApproval"("bookingId", "createdAt");
CREATE INDEX "ClosureWindow_propertyId_startAt_endAt_idx" ON "ClosureWindow"("propertyId", "startAt", "endAt");
CREATE INDEX "Notification_userId_readAt_createdAt_idx" ON "Notification"("userId", "readAt", "createdAt");
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_requestingDepartmentId_fkey" FOREIGN KEY ("requestingDepartmentId") REFERENCES "Department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BookingResource" ADD CONSTRAINT "BookingResource_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BookingResource" ADD CONSTRAINT "BookingResource_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BookingApproval" ADD CONSTRAINT "BookingApproval_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BookingApproval" ADD CONSTRAINT "BookingApproval_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ClosureWindow" ADD CONSTRAINT "ClosureWindow_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_time_check" CHECK ("endAt" > "startAt");
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_attendee_check" CHECK ("attendeeCount" >= 0);
ALTER TABLE "BookingResource" ADD CONSTRAINT "BookingResource_time_check" CHECK ("endAt" > "startAt");
ALTER TABLE "ClosureWindow" ADD CONSTRAINT "ClosureWindow_time_check" CHECK ("endAt" > "startAt");
ALTER TABLE "BookingResource" ADD CONSTRAINT "BookingResource_no_approved_overlap" EXCLUDE USING gist ("propertyId" WITH =, tsrange("startAt", "endAt", '[)') WITH &&) WHERE ("status" = 'APPROVED');
