'use client';
import { useCallback, useEffect, useState } from 'react';
import { EmptyState } from '../../../components/ui';
type Option = { id: string; displayName?: string; propertyCode?: string; name?: string };
type Allocation = { id: string; referenceNumber: string; responsiblePerson?: string; status: string; requestDate: string; startDate?: string; endDate?: string; property: { displayName: string; propertyCode: string; inventoryAssignments: unknown[] }; department: { id: string; name: string }; history: Array<{ id: string; fromStatus?: string; toStatus: string; effectiveAt: string; reason?: string; actor: { displayName: string } }> };
type Envelope<T> = { data?: T; error?: { message: string } };
function csrf(): string { return decodeURIComponent(document.cookie.split('; ').find((x) => x.startsWith('ems_csrf_token='))?.split('=')[1] ?? ''); }
export default function AllocationsPage(): React.ReactElement { const [rows, setRows] = useState<Allocation[]>([]); const [properties, setProperties] = useState<Option[]>([]); const [departments, setDepartments] = useState<Option[]>([]); const [permissions, setPermissions] = useState<string[]>([]); const [message, setMessage] = useState<string>(); const load = useCallback(async () => { const p = await fetch('/api/v1/allocations?pageSize=100').then((r) => r.json()) as Envelope<Allocation[]>; setRows(p.data ?? []); }, []); useEffect(() => { void fetch('/api/v1/allocations?pageSize=100').then((r) => r.json()).then((p: Envelope<Allocation[]>) => setRows(p.data ?? [])); void fetch('/api/v1/properties?pageSize=100').then((r) => r.json()).then((p: Envelope<Option[]>) => setProperties(p.data ?? [])); void fetch('/api/v1/master-data/departments?pageSize=100').then((r) => r.json()).then((p: Envelope<Option[]>) => setDepartments(p.data ?? [])); void fetch('/api/v1/auth/session').then((r) => r.json()).then((p: Envelope<{ user?: { permissions: string[] } }>) => setPermissions(p.data?.user?.permissions ?? [])); }, []);
  async function create(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const response = await fetch('/api/v1/allocations', { method: 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify({ propertyId: form.get('propertyId'), departmentId: form.get('departmentId'), responsiblePerson: form.get('responsiblePerson') || undefined, requestDate: new Date(), submit: true }) }); const p = await response.json() as Envelope<unknown>; setMessage(response.ok ? 'Allocation submitted.' : p.error?.message); if (response.ok) { formElement.reset(); await load(); } }
  async function action(row: Allocation, name: string): Promise<void> { let body: Record<string, unknown> = {}; if (['vacate', 'cancel'].includes(name)) { const reason = window.prompt('Reason'); if (!reason) return; body = { reason }; } if (name === 'reassign') { const departmentId = window.prompt('New department ID'); const reason = window.prompt('Reason'); if (!departmentId || !reason) return; body = { departmentId, reason }; } const response = await fetch(`/api/v1/allocations/${row.id}/${name}`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify(body) }); const p = await response.json() as Envelope<unknown>; setMessage(response.ok ? `Allocation ${name} completed.` : p.error?.message); if (response.ok) await load(); }
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">Office allocations</h1><p className="text-sm text-slate-600">Approval, activation, reassignment, vacation, and immutable allocation history.</p></header><section className="rounded-2xl border bg-white p-4 shadow-sm"><form onSubmit={create} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select required name="propertyId" className="rounded-lg border bg-transparent px-3 py-2"><option value="">Office property</option>{properties.map((x) => <option key={x.id} value={x.id}>{x.propertyCode} — {x.displayName}</option>)}</select><select required name="departmentId" className="rounded-lg border bg-transparent px-3 py-2"><option value="">Department</option>{departments.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="responsiblePerson" placeholder="Responsible officer" className="rounded-lg border bg-transparent px-3 py-2"/><button className="rounded-lg bg-red-600 px-4 py-2 font-medium text-white">Submit allocation</button></form>{message ? <p role="status" className="mt-3 text-sm">{message}</p> : null}</section>{rows.length===0?<div className="app-card"><EmptyState title="No office allocations" description="Submit an allocation above. Approval and occupancy history will appear here."/></div>:null}<section className="space-y-4">{rows.map((row) => <article key={row.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><strong>{row.referenceNumber}</strong><p>{row.property.propertyCode} — {row.property.displayName}</p><p className="text-sm text-slate-500">{row.department.name}{row.responsiblePerson ? ` · ${row.responsiblePerson}` : ''} · Inventory: {row.property.inventoryAssignments.length}</p></div><span className="font-medium">{row.status.replaceAll('_', ' ')}</span></div><div className="mt-3 flex flex-wrap gap-3 text-sm">{row.status === 'PENDING_APPROVAL' && permissions.includes('allocation.approve') ? <button onClick={() => void action(row, 'approve')} className="text-green-700">Approve</button> : null}{row.status === 'APPROVED' && permissions.includes('allocation.manage') ? <button onClick={() => void action(row, 'activate')} className="text-blue-700">Activate</button> : null}{row.status === 'ACTIVE' && permissions.includes('allocation.manage') ? <><button onClick={() => void action(row, 'vacate')} className="text-red-700">Vacate</button><button onClick={() => void action(row, 'reassign')} className="text-blue-700">Reassign</button></> : null}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-medium">History ({row.history.length})</summary><ol className="mt-2 space-y-2 border-l pl-4 text-sm">{row.history.map((h) => <li key={h.id}>{h.fromStatus ? `${h.fromStatus} → ` : ''}{h.toStatus} · {h.actor.displayName}{h.reason ? ` · ${h.reason}` : ''}</li>)}</ol></details></article>)}</section></div>; }

