CREATE TYPE "AllocationStatus" AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ACTIVE', 'REASSIGNED', 'VACATED', 'CANCELLED');
CREATE TABLE "Allocation" ("id" TEXT NOT NULL, "referenceNumber" TEXT NOT NULL, "propertyId" TEXT NOT NULL, "departmentId" TEXT NOT NULL, "responsiblePerson" TEXT, "requestDate" TIMESTAMP(3) NOT NULL, "startDate" TIMESTAMP(3), "endDate" TIMESTAMP(3), "status" "AllocationStatus" NOT NULL DEFAULT 'DRAFT', "approvedBy" TEXT, "approvedAt" TIMESTAMP(3), "notes" TEXT, "createdBy" TEXT NOT NULL, "updatedBy" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Allocation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AllocationHistory" ("id" TEXT NOT NULL, "allocationId" TEXT NOT NULL, "fromStatus" "AllocationStatus", "toStatus" "AllocationStatus" NOT NULL, "departmentId" TEXT NOT NULL, "responsiblePerson" TEXT, "effectiveAt" TIMESTAMP(3) NOT NULL, "reason" TEXT, "actorUserId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AllocationHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InventoryItem" ("id" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "replacementCost" DECIMAL(14,2), "isEnabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InventoryItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PropertyInventory" ("id" TEXT NOT NULL, "propertyId" TEXT NOT NULL, "itemId" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "condition" TEXT NOT NULL, "serialNumber" TEXT, "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "returnedAt" TIMESTAMP(3), CONSTRAINT "PropertyInventory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InventoryMovement" ("id" TEXT NOT NULL, "propertyInventoryId" TEXT NOT NULL, "movementType" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "condition" TEXT NOT NULL, "notes" TEXT, "actorUserId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InventoryMovement_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Allocation_referenceNumber_key" ON "Allocation"("referenceNumber");
CREATE INDEX "Allocation_propertyId_status_idx" ON "Allocation"("propertyId", "status");
CREATE INDEX "Allocation_departmentId_status_idx" ON "Allocation"("departmentId", "status");
CREATE INDEX "Allocation_createdAt_idx" ON "Allocation"("createdAt");
CREATE UNIQUE INDEX "Allocation_one_active_property" ON "Allocation"("propertyId") WHERE "status" = 'ACTIVE';
CREATE INDEX "AllocationHistory_allocationId_createdAt_idx" ON "AllocationHistory"("allocationId", "createdAt");
CREATE INDEX "AllocationHistory_departmentId_effectiveAt_idx" ON "AllocationHistory"("departmentId", "effectiveAt");
CREATE UNIQUE INDEX "InventoryItem_code_key" ON "InventoryItem"("code");
CREATE INDEX "PropertyInventory_propertyId_returnedAt_idx" ON "PropertyInventory"("propertyId", "returnedAt");
CREATE INDEX "PropertyInventory_itemId_idx" ON "PropertyInventory"("itemId");
CREATE INDEX "InventoryMovement_propertyInventoryId_createdAt_idx" ON "InventoryMovement"("propertyInventoryId", "createdAt");
ALTER TABLE "Allocation" ADD CONSTRAINT "Allocation_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Allocation" ADD CONSTRAINT "Allocation_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Allocation" ADD CONSTRAINT "Allocation_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Allocation" ADD CONSTRAINT "Allocation_approvedBy_fkey" FOREIGN KEY ("approvedBy") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AllocationHistory" ADD CONSTRAINT "AllocationHistory_allocationId_fkey" FOREIGN KEY ("allocationId") REFERENCES "Allocation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AllocationHistory" ADD CONSTRAINT "AllocationHistory_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PropertyInventory" ADD CONSTRAINT "PropertyInventory_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PropertyInventory" ADD CONSTRAINT "PropertyInventory_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "InventoryItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_propertyInventoryId_fkey" FOREIGN KEY ("propertyInventoryId") REFERENCES "PropertyInventory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Allocation" ADD CONSTRAINT "Allocation_dates_check" CHECK ("endDate" IS NULL OR "startDate" IS NULL OR "endDate" >= "startDate");
ALTER TABLE "PropertyInventory" ADD CONSTRAINT "PropertyInventory_quantity_check" CHECK ("quantity" > 0);
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_quantity_check" CHECK ("quantity" > 0);
