'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
type Property = { id: string; propertyCode: string; displayName: string };
type Booking = { id: string; referenceNumber: string; requesterName: string; purpose: string; startAt: string; endAt: string; status: string; resources: Array<{ property: Property }> };
type Envelope<T> = { data?: T; error?: { message: string } };
function csrf(): string { return decodeURIComponent(document.cookie.split('; ').find((x) => x.startsWith('ems_csrf_token='))?.split('=')[1] ?? ''); }

export default function BookingsPage(): React.ReactElement {
  const [rows, setRows] = useState<Booking[]>([]); const [properties, setProperties] = useState<Property[]>([]); const [permissions, setPermissions] = useState<string[]>([]); const [view, setView] = useState<'agenda' | 'calendar'>('agenda'); const [message, setMessage] = useState<string>();
  const load = useCallback(async () => { const payload = await fetch('/api/v1/bookings?pageSize=100&sort=startAt&order=asc').then((r) => r.json()) as Envelope<Booking[]>; setRows(payload.data ?? []); }, []);
  useEffect(() => { void fetch('/api/v1/bookings?pageSize=100&sort=startAt&order=asc').then((r) => r.json()).then((p: Envelope<Booking[]>) => setRows(p.data ?? [])); void fetch('/api/v1/properties?pageSize=100').then((r) => r.json()).then((p: Envelope<Property[]>) => setProperties(p.data ?? [])); void fetch('/api/v1/auth/session').then((r) => r.json()).then((p: Envelope<{ user?: { permissions: string[] } }>) => setPermissions(p.data?.user?.permissions ?? [])); }, []);
  const grouped = useMemo(() => Object.entries(rows.reduce<Record<string, Booking[]>>((groups, row) => { const date = new Date(row.startAt).toLocaleDateString('en-PK', { timeZone: 'Asia/Karachi', dateStyle: 'medium' }); (groups[date] ??= []).push(row); return groups; }, {})), [rows]);
  async function create(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const form = new FormData(event.currentTarget); const startAt = new Date(String(form.get('startAt'))); const endAt = form.get('endAt') ? new Date(String(form.get('endAt'))) : new Date(startAt.getTime() + 3 * 60 * 60 * 1000); const body = { resourceIds: form.getAll('resourceIds'), requesterName: form.get('requesterName'), purpose: form.get('purpose'), startAt, endAt, attendeeCount: Number(form.get('attendeeCount') ?? 0), isPaid: false, submit: true, idempotencyKey: crypto.randomUUID() }; const response = await fetch('/api/v1/bookings', { method: 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify(body) }); const payload = await response.json() as Envelope<unknown>; setMessage(response.ok ? 'Booking submitted for approval.' : payload.error?.message ?? 'Unable to submit booking'); if (response.ok) { event.currentTarget.reset(); await load(); } }
  async function action(id: string, name: 'approve' | 'reject' | 'cancel'): Promise<void> { const reason = name === 'approve' ? undefined : window.prompt(`${name === 'reject' ? 'Rejection' : 'Cancellation'} reason`); if (name !== 'approve' && !reason) return; const response = await fetch(`/api/v1/bookings/${id}/${name}`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify(name === 'reject' ? { reason } : name === 'cancel' ? { reason } : {}) }); const payload = await response.json() as Envelope<unknown>; setMessage(response.ok ? `Booking ${name}d.` : payload.error?.message ?? 'Action failed'); if (response.ok) await load(); }
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Bookings</h1><p className="text-sm text-slate-600 dark:text-slate-300">Classrooms, workshops, auditoriums, Executive Club, and lawns.</p></div><div className="flex rounded-lg border p-1"><button onClick={() => setView('agenda')} className={`rounded px-3 py-1 text-sm ${view === 'agenda' ? 'bg-red-600 text-white' : ''}`}>Agenda</button><button onClick={() => setView('calendar')} className={`rounded px-3 py-1 text-sm ${view === 'calendar' ? 'bg-red-600 text-white' : ''}`}>Calendar</button></div></header>
    <section className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-900"><h2 className="font-semibold">New booking request</h2><form onSubmit={create} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input required name="requesterName" placeholder="Requester name" className="rounded-lg border bg-transparent px-3 py-2"/><input required name="purpose" placeholder="Purpose" className="rounded-lg border bg-transparent px-3 py-2"/><select required multiple name="resourceIds" aria-label="Resources" className="min-h-24 rounded-lg border bg-transparent px-3 py-2">{properties.map((p) => <option key={p.id} value={p.id}>{p.propertyCode} — {p.displayName}</option>)}</select><div className="grid gap-2"><label className="text-xs">Start<input required name="startAt" type="datetime-local" className="mt-1 w-full rounded-lg border bg-transparent px-3 py-2"/></label><label className="text-xs">End (defaults to 3 hours)<input name="endAt" type="datetime-local" className="mt-1 w-full rounded-lg border bg-transparent px-3 py-2"/></label></div><input name="attendeeCount" type="number" min="0" placeholder="Attendees" className="rounded-lg border bg-transparent px-3 py-2"/><button className="rounded-lg bg-red-600 px-4 py-2 font-medium text-white">Submit request</button></form>{message ? <p role="status" className="mt-3 text-sm">{message}</p> : null}</section>
    <section className={view === 'calendar' ? 'grid gap-4 md:grid-cols-2 xl:grid-cols-3' : 'space-y-4'}>{grouped.map(([date, bookings]) => <article key={date} className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-900"><h2 className="font-semibold">{date}</h2><div className="mt-3 space-y-3">{(bookings ?? []).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between gap-3"><strong>{row.referenceNumber}</strong><span>{row.status.replaceAll('_', ' ')}</span></div><p className="mt-1">{row.purpose} — {row.requesterName}</p><p className="text-slate-500">{new Date(row.startAt).toLocaleTimeString('en-PK', { timeZone: 'Asia/Karachi', hour: '2-digit', minute: '2-digit' })}–{new Date(row.endAt).toLocaleTimeString('en-PK', { timeZone: 'Asia/Karachi', hour: '2-digit', minute: '2-digit' })} · {row.resources.map((r) => r.property.displayName).join(', ')}</p><div className="mt-2 flex gap-3">{row.status === 'PENDING_APPROVAL' && permissions.includes('booking.approve') ? <button onClick={() => void action(row.id, 'approve')} className="text-green-700">Approve</button> : null}{row.status === 'PENDING_APPROVAL' && permissions.includes('booking.reject') ? <button onClick={() => void action(row.id, 'reject')} className="text-red-700">Reject</button> : null}{['DRAFT', 'PENDING_APPROVAL', 'APPROVED'].includes(row.status) ? <button onClick={() => void action(row.id, 'cancel')} className="text-slate-600">Cancel</button> : null}</div></div>)}</div></article>)}</section></div>;
}
